packages:
  - .
  - examples/with-nextjs-appdir
  - examples/with-nextjs
  - examples/with-express
  - examples/with-serverless
  - examples/with-fastify
  - examples/with-nuxtjs

onlyBuiltDependencies:
  - esbuild
